name: Build Resume PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Copy PDF to build directory
        run: |
          mkdir -p build
          cp resume.pdf build/

      - name: Commit and push PDF to build directory
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update built resume.pdf [ci skip]'
          file_pattern: 'build/resume.pdf'
          branch: ${{ github.ref_name }}
